### ISSUE TITLE
Str::ascii does not always work as expected

### ISSUE THREAD

**Issue by drm** [zicht/util#1]
See https://github.com/zicht/url-bundle/issues/6

**Comment by DoNormal** [comment]
`iconv` seems to be dependant on the server locale. I can't reproduce the bug with a failing test, even if I call `setlocale` manually.

However, when I create a new page and throw out some var_dumps, this is the result:

![image](https://cloud.githubusercontent.com/assets/596975/22065592/46f97500-dd89-11e6-9b9c-5a40253ebf08.png)

**Comment by drm** [comment]
I am fine with replacing the implementation with transliterate if that seems works better. As long as there's a test for it.

**Comment by drm** [comment]
fixed
